language: go
install: true
sudo: required
go:
  - 1.7
  - 1.8
  - 1.9
  - master
install:
  - go get github.com/Sirupsen/logrus
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
